version: 2
registries:
  mvn:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt
    username: x-access-token
    password: ${{secrets.READER_TOKEN}}
  npm:
    type: npm-registry
    url: https://npm.pkg.github.com/
    username: x-access-token
    password: ${{secrets.READER_TOKEN}}
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - "mvn"
    groups:
      maven:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - "npm"
    groups:
      npm:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
