name: Automerge Dependabot Pull Requests
description: Automatically merge pull requests created by Dependabot with configurable rules and workflow summary
author: navikt
version: 1.0.0

branding:
  icon: git-merge
  color: green

inputs:
  token:
    description: The name of the variable that contains the GitHub token
    required: true
    default: 'GITHUB_TOKEN'
  minimum-age-of-pr:
    description: The minimum age of the pull request in days before it can be automerged
    required: false
    default: '0'
  blackout-periods:
    description: Periods of time, months, or days when the action should not run (e.g., "Dec 24-Jan 5", "Sat,Sun", "9:00-17:00")
    required: false
  ignored-dependencies:
    description: Comma-separated list of dependencies to ignore (will not be automerged)
    required: false
  always-allow:
    description: Comma-separated list of patterns to always allow. Use * to always allow all non-semver dependencies, or specify patterns like 'name:string' to match dependencies containing a specific string
    required: false
  ignored-versions:
    description: Comma-separated list of specific versions to ignore (format package@version, e.g., "lodash@4.17.21,axios@0.21.1")
    required: false
  semver-filter:
    description: Filter based on semver level changes (comma-separated list of major, minor, patch, unknown)
    required: false
    default: 'patch,minor'
  merge-method:
    description: The merge method to use (merge, squash, rebase). Note that only 'merge' method is supported with GitHub merge queues.
    required: false
    default: 'merge'

runs:
  using: node20
  main: dist/index.js
